spring:
  application:
    name: tams
  main:
    banner-mode: log

  datasource:
    url: jdbc:mysql://localhost:3306/tams_dev?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8999
  servlet:
    context-path: /

websocket:
  path: /websocket
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    username: root
    password: root
    name: tams_dev

logging:
  path: ${SKMC_HOME}/log/
  level:
    root: INFO
    com:
      shavika: INFO
