spring:
  application:
    name: shavika-server-websocket
  main:
    banner-mode: log

server:
  port: 8999
  servlet:
    context-path: /

websocket:
  path: /websocket
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: tams-db-inst-dev-do-user-21795668-0.g.db.ondigitalocean.com
    port: 25060
    username: tams_user
    password: AVNS_aNo8ipoyuf3SmYEbIlA
    name: tams_database

logging:
  path: ${SKMC_HOME}/log/
  level:
    root: INFO
    com:
      tams: INFO

app:
  token-expiry-minutes: 30
  allowed-origins:
    - http://localhost:3000
    - http://localhost:4000
    - http://localhost:5173
    - https://app.merav.co.in
