spring:
  application:
    name: shavika-server-websocket
  main:
    banner-mode: log

server:
  port: 8999
  servlet:
    context-path: /

websocket:
  path: /websocket
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    username: tams_user1
    password: tams_user1
    name: tams_java1

logging:
  path: ${SKMC_HOME}/log/
  level:
    root: INFO
    com:
      tams: INFO

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
