name: 2. doctl - Provision Container Registry

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment selection"
        required: true
        type: environment
        default: "dev"

permissions:
  contents: write

jobs:
  provision:
    name: Provision and Deployment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      packages: read

    steps:
      # Step 0: Install required softwares on ubuntu-latest
      - name: Install required software-package
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Step 1: Install and authenticate doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Debug Information
        run: |
          echo environment: ${{ inputs.environment || 'N/A' }}
          echo INSTANCE_NAME: ${{ vars.DB_INSTANCE_NAME }}

        # Step 2: check is Registry exists
      - name: Check if Container Registry is Exists
        run: |
          REGISTRY_ID=$(doctl registry get ${{ vars.DOCR_REGISTRY_NAME }} --format Name,Endpoint --no-header | grep ${{ vars.DOCR_REGISTRY_NAME }} | awk '{print $1}')
          if [[ -n "$REGISTRY_ID" ]]; then
            echo "✅ Container Registry already exists with ID: $REGISTRY_ID"
            echo "REGISTRY_EXISTS=true" >> $GITHUB_ENV
            echo "REGISTRY_ID=$REGISTRY_ID" >> $GITHUB_ENV
          else
            echo "❌ Container Registry does not exist."
            echo "REGISTRY_EXISTS=false" >> $GITHUB_ENV
          fi

      # Step 3: Create the Container Registry on DigitalOcean
      - name: Create DO Container Registry
        if: env.REGISTRY_EXISTS == 'false'
        shell: bash
        run: |
          set -euo pipefail
          echo "Creating container registry '${{ vars.DOCR_REGISTRY_NAME }}'..."
          
          # Create the container registry in blr1 (Bangalore), BASIC
          doctl registry create ${{ vars.DOCR_REGISTRY_NAME }} --region blr1 --subscription-tier basic
          echo "Registry created."
